name: Test Run
on:
  push
jobs:
  lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: echo "THIS IS A TEST PACKAGE" > file.txt
      - run: zip lambda.zip file.txt
      - uses: stcalica/update-lambda
        with:
          package: lambda.zip
          function-name: DEREK-TEST-FUNCTION
          AWS_REGION: us-east-1
          AWS_SECRET_ID: 908115985148
          AWS_SECRET_KEY: AKIA5G37OIL6IXDZQEMR